{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "pagespeed-exporter.fullname" . }}
  labels:
  {{- include "pagespeed-exporter.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: api-call
              image: curlimages/curl
              args:
                - -sSv
                - -H
                - "X-Prometheus-ScrapeResult-Timeout-Seconds: {{ .Values.cronjob.scrapeResultTimeoutSeconds }}"
                - "http://{{ include "pagespeed-exporter.fullname" . }}:{{ .Values.service.port }}/probe?target={{- join "&target=" .Values.exporter.targets }}"
          restartPolicy: OnFailure
{{- end }}